# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chenyuwei/Desktop/修改/one-to-one--sse-experiment-Ruofan_Li/VLSE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chenyuwei/Desktop/修改/one-to-one--sse-experiment-Ruofan_Li/VLSE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chenyuwei/Desktop/修改/one-to-one--sse-experiment-Ruofan_Li/VLSE/CMakeFiles /Users/chenyuwei/Desktop/修改/one-to-one--sse-experiment-Ruofan_Li/VLSE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chenyuwei/Desktop/修改/one-to-one--sse-experiment-Ruofan_Li/VLSE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named test_triple_vf

# Build rule for target.
test_triple_vf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_triple_vf
.PHONY : test_triple_vf

# fast build rule for target.
test_triple_vf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_triple_vf.dir/build.make CMakeFiles/test_triple_vf.dir/build
.PHONY : test_triple_vf/fast

#=============================================================================
# Target rules for targets named main_triple

# Build rule for target.
main_triple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_triple
.PHONY : main_triple

# fast build rule for target.
main_triple/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/build
.PHONY : main_triple/fast

Vacuum-Filter/test.o: Vacuum-Filter/test.cpp.o
.PHONY : Vacuum-Filter/test.o

# target to build an object file
Vacuum-Filter/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Vacuum-Filter/test.cpp.o
.PHONY : Vacuum-Filter/test.cpp.o

Vacuum-Filter/test.i: Vacuum-Filter/test.cpp.i
.PHONY : Vacuum-Filter/test.i

# target to preprocess a source file
Vacuum-Filter/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Vacuum-Filter/test.cpp.i
.PHONY : Vacuum-Filter/test.cpp.i

Vacuum-Filter/test.s: Vacuum-Filter/test.cpp.s
.PHONY : Vacuum-Filter/test.s

# target to generate assembly for a file
Vacuum-Filter/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Vacuum-Filter/test.cpp.s
.PHONY : Vacuum-Filter/test.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/main.cpp.s
.PHONY : main.cpp.s

src/Pub_para.o: src/Pub_para.cpp.o
.PHONY : src/Pub_para.o

# target to build an object file
src/Pub_para.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/src/Pub_para.cpp.o
.PHONY : src/Pub_para.cpp.o

src/Pub_para.i: src/Pub_para.cpp.i
.PHONY : src/Pub_para.i

# target to preprocess a source file
src/Pub_para.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/src/Pub_para.cpp.i
.PHONY : src/Pub_para.cpp.i

src/Pub_para.s: src/Pub_para.cpp.s
.PHONY : src/Pub_para.s

# target to generate assembly for a file
src/Pub_para.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/src/Pub_para.cpp.s
.PHONY : src/Pub_para.cpp.s

src/database.o: src/database.cpp.o
.PHONY : src/database.o

# target to build an object file
src/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/src/database.cpp.o
.PHONY : src/database.cpp.o

src/database.i: src/database.cpp.i
.PHONY : src/database.i

# target to preprocess a source file
src/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/src/database.cpp.i
.PHONY : src/database.cpp.i

src/database.s: src/database.cpp.s
.PHONY : src/database.s

# target to generate assembly for a file
src/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/src/database.cpp.s
.PHONY : src/database.cpp.s

src/util.o: src/util.cpp.o
.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_triple.dir/build.make CMakeFiles/main_triple.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

test_triple_vf.o: test_triple_vf.cpp.o
.PHONY : test_triple_vf.o

# target to build an object file
test_triple_vf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_triple_vf.dir/build.make CMakeFiles/test_triple_vf.dir/test_triple_vf.cpp.o
.PHONY : test_triple_vf.cpp.o

test_triple_vf.i: test_triple_vf.cpp.i
.PHONY : test_triple_vf.i

# target to preprocess a source file
test_triple_vf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_triple_vf.dir/build.make CMakeFiles/test_triple_vf.dir/test_triple_vf.cpp.i
.PHONY : test_triple_vf.cpp.i

test_triple_vf.s: test_triple_vf.cpp.s
.PHONY : test_triple_vf.s

# target to generate assembly for a file
test_triple_vf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_triple_vf.dir/build.make CMakeFiles/test_triple_vf.dir/test_triple_vf.cpp.s
.PHONY : test_triple_vf.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... main_triple"
	@echo "... test_triple_vf"
	@echo "... Vacuum-Filter/test.o"
	@echo "... Vacuum-Filter/test.i"
	@echo "... Vacuum-Filter/test.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Pub_para.o"
	@echo "... src/Pub_para.i"
	@echo "... src/Pub_para.s"
	@echo "... src/database.o"
	@echo "... src/database.i"
	@echo "... src/database.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... test_triple_vf.o"
	@echo "... test_triple_vf.i"
	@echo "... test_triple_vf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

